"use client";
import Link from "next/link";import { useRouter } from "next/navigation";import { useState } from "react";import { Search,ShieldCheck,BadgeDollarSign,Clock3,Star } from "lucide-react";import { categories,categoryIcons } from "@/lib/data";import { JobCard } from "@/components/JobCard";import { useApp } from "@/components/AppProvider";
export default function Home(){const [q,setQ]=useState("");const router=useRouter();const {jobs}=useApp();return <>
<section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">One price. Zero bidding.</span><h1>Small jobs.<br/><em>Done for $100.</em></h1><p>Connect with reliable local pros for the quick fixes and tasks that keep your home moving.</p><form className="search" onSubmit={e=>{e.preventDefault();router.push(`/jobs?q=${encodeURIComponent(q)}`)}}><Search/><input aria-label="Search" placeholder="Enter ZIP code or service" value={q} onChange={e=>setQ(e.target.value)}/><button>Find jobs</button></form><div className="trust"><span><ShieldCheck/> Verified workers</span><span><BadgeDollarSign/> Fixed $100 price</span><span><Clock3/> Quick turnaround</span></div></div><div className="hero-card"><div className="worker-avatar">AM</div><div><b>Alex M.</b><span>Top-rated handyman</span><span className="stars">★★★★★ <small>4.9 (82)</small></span></div><div className="mini-job"><span>Today’s job</span><b>Mount a 55” TV</b><strong>$100</strong></div></div></div></section>
<section className="section wrap"><div className="section-head"><div><span className="eyebrow">Popular services</span><h2>What can we help with?</h2></div><Link href="/jobs" className="text-link">Browse all jobs →</Link></div><div className="categories">{categories.map(c=><Link href={`/jobs?category=${c}`} className="category" key={c}><span>{categoryIcons[c]}</span><b>{c}</b><small>Small {c.toLowerCase()} jobs</small></Link>)}</div></section>
<section className="section soft"><div className="wrap"><div className="center"><span className="eyebrow">Simple by design</span><h2>From to-do to done</h2></div><div className="steps">{[["1","Post your job","Describe the task, add photos, and choose a date."],["2","A pro claims it","A qualified local worker accepts your $100 job."],["3","Get it done","Chat, coordinate, and approve the finished work."],["4","Pay & review","Release the secure payment and share feedback."]].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
<section className="section wrap"><div className="section-head"><div><span className="eyebrow">Near you</span><h2>Fresh $100 jobs</h2></div><Link className="text-link" href="/jobs">See all →</Link></div><div className="job-grid">{jobs.filter(j=>j.status==="Posted").slice(0,3).map(j=><JobCard key={j.id} job={j}/>)}</div></section>
<section className="quote"><div className="wrap quote-inner"><Star fill="currentColor"/><blockquote>“I’d put off these little repairs for months. The price was clear, the worker was great, and all three were finished before lunch.”</blockquote><span>— Danielle, homeowner in Austin</span></div></section>
<section className="cta"><div><h2>One small job. One fair price.</h2><p>Post in under five minutes. A local pro can take it from there.</p></div><Link href="/post" className="button light">Post your job for $100</Link></section></>}
